# Generated by Django 3.1.3 on 2020-12-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service',
            new_name='friendly_name',
        ),
        migrations.AlterField(
            model_name='servicesdetail',
            name='is_a_service',
            field=models.BooleanField(default=True),
        ),
    ]
