# Generated by Django 3.1.3 on 2020-12-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201216_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_a_service',
            field=models.BooleanField(default=False),
        ),
    ]
