# Generated by Django 3.1.3 on 2020-12-25 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201216_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
