# Generated by Django 3.1.3 on 2020-12-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_a_service',
        ),
    ]
